// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
)

func (ph *Phone) User(ctx context.Context) (*User, error) {
	result, err := ph.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = ph.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Phone(ctx context.Context) (*Phone, error) {
	result, err := u.Edges.PhoneOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryPhone().Only(ctx)
	}
	return result, MaskNotFound(err)
}
