// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/spacelions/phew/users/ent/phone"
	"github.com/spacelions/phew/users/ent/schema"
	"github.com/spacelions/phew/users/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	phoneFields := schema.Phone{}.Fields()
	_ = phoneFields
	// phoneDescNumber is the schema descriptor for number field.
	phoneDescNumber := phoneFields[0].Descriptor()
	// phone.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	phone.NumberValidator = phoneDescNumber.Validators[0].(func(string) error)
	// phoneDescCountryCode is the schema descriptor for country_code field.
	phoneDescCountryCode := phoneFields[1].Descriptor()
	// phone.DefaultCountryCode holds the default value on creation for the country_code field.
	phone.DefaultCountryCode = phoneDescCountryCode.Default.(string)
	// phone.CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	phone.CountryCodeValidator = phoneDescCountryCode.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[1].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
